// ── Content (shareable) ─────────────────────────────────────────────────────

export interface FileEntry {
  name: string;
  data: string; // base64
  mimeType: string;
}

export interface EmbedEntry {
  id: string;
  url: string;       // original URL as pasted by user
  title?: string;    // fetched via oEmbed at add time
  embedUrl?: string; // resolved iframe src, stored to avoid re-fetching
}

export interface CardReferenceAttachment {
  type: 'card';
  id: string;          // local UUID — fast path
  guid: string;        // stable guid — cross-device
  externalId?: string; // TheSession etc. — portable
  title: string;       // snapshot of card name, fallback if unresolved
}

export type Attachment =
  | ({ type: 'file' } & FileEntry & {
      /** Multi-tune ABC files only: which splitAbcTunes() index to open by
       *  default — a per-attachment "favorite version", set explicitly from
       *  the preview modal. Absent = today's default (index 0). */
      preferredIndex?: number;
      /** Set when this attachment was generated by fetching an external
       *  source (currently only 'thesession', via tuneResultToCard's ABC
       *  file) — lets a "Refresh ABC" action find-and-replace it precisely
       *  instead of guessing by filename (fragile: breaks if the card was
       *  renamed since import). Absent on manually-added or pre-existing
       *  attachments; never touched by anything except the fetch that
       *  (re)generates it. */
      generatedBy?: 'thesession';
    })
  | ({ type: 'embed' } & EmbedEntry)
  | CardReferenceAttachment;

export interface Card {
  id: string;
  guid: string;
  name: string;
  defaultImportance: number; // default: 1
  tags: string[];
  externalId?: string; // e.g. "thesession:1197"
  content: {
    notes: string;
    attachments: Attachment[];
  };
}

export interface DeckEntry {
  cardId: string;
  importance?: number; // deck-specific importance; falls back to card.defaultImportance when absent
}

export interface Deck {
  id: string;
  name: string;
  entries: DeckEntry[];
  favorite?: boolean;
}

// ── Personal data ────────────────────────────────────────────────────────────

/** Maps directly to FSRS grades: 1=Again · 2=Hard · 3=Good · 4=Easy */
export type SessionRating = 'again' | 'hard' | 'good' | 'easy';

export interface SessionEntry {
  ts: number;           // timestamp in ms
  rating: SessionRating;
}

export interface Profile {
  id: string;
  name: string;
}

export interface CardWork {
  profileId: string;
  cardId: string;
  history: SessionEntry[];
}

export interface Folder {
  id: string;
  name: string;
  folderIds: string[];
  deckIds: string[];
}

// ── User = entire state for one person ───────────────────────────────────────

export interface User {
  // Identity
  id: string;
  name: string;
  language: 'en' | 'fr';

  // Study settings
  availabilityThreshold: number;
  weightByImportance: boolean;
  /** Exclude mastered cards from study picks (default true). Off = study as if
   *  the mastery threshold were 100% — study flow only, deck metrics keep the
   *  real threshold. */
  excludeMastered?: boolean;
  forgettingRate: number; // λ: scales S → S/λ for scheduling; 1 = FSRS default, >1 = faster forgetting

  // Profiles
  profileIds: string[];
  currentProfileId: string;
  profiles: Record<string, Profile>;

  // Content
  cards: Record<string, Card>;
  decks: Record<string, Deck>;
  cardWorks: Record<string, CardWork>; // key: `${profileId}:${cardId}`
  folders: Record<string, Folder>;
  rootFolderIds: string[];
  rootDeckIds: string[];

  /** Per-module extension data, synced with the rest of this blob (Drive,
   *  IndexedDB) — e.g. the Sessions feature's recorded-session metadata
   *  (see session/model.ts's TuneAnalyserModuleData). Loosely typed here
   *  (types.ts is foundational and shouldn't depend on any one module's
   *  shape); each module casts its own key via its own typed accessor. Keep
   *  entries small — this whole object is structuredClone'd on every
   *  mutate() call across the app (store.ts) — large/binary data (audio,
   *  crash-recovery scratch) belongs in a module's own local-only database
   *  instead, never here. */
  modules?: Record<string, unknown>;

  // Schema versioning
  schemaVersion?: number;
}

/** AppState is the active User — kept as alias to minimise call-site changes. */
export type AppState = User;

// ── Routing ──────────────────────────────────────────────────────────────────

export type StudyStrategy = 'random' | 'optimal' | 'stochastic';

export type FilterState = 'include' | 'exclude';

export type LibrarySort = 'alpha' | 'lastReviewed' | 'lastAdded' | 'importance' | 'recall' | 'difficulty';

export type TrendingGainMode = 'absolute' | 'percent';

export type Route =
  | { view: 'folder'; folderId: string | null }
  | { view: 'library'; search?: string; tags?: [string, FilterState][]; decks?: [string, FilterState][]; sort?: LibrarySort; sortAsc?: boolean; tagOr?: boolean; deckOr?: boolean }
  | { view: 'deck'; deckId: string }
  | { view: 'card'; cardId: string; contextDeckId?: string }
  | { view: 'study'; deckId?: string; cardIds?: string[]; studyTitle?: string; strategy: StudyStrategy; currentCardId?: string | null; contextDeckId?: string | null }
  | { view: 'modules' }
  | { view: 'sessions'; sessionId?: string }
  // `from`/`to` are YYYY-MM-DD, snapped to the closest synced snapshot on load.
  // Deliberately excludes the deck-picker target — that stays session-only, never persisted.
  | { view: 'trending'; from?: string; to?: string; gainMode?: TrendingGainMode; minTunebooks?: number };

export interface AppContext {
  user: AppState;
  route: Route;
  navigate: (route: Route) => void;
  back: () => void;
  forward: () => void;
  canGoBack: boolean;
  canGoForward: boolean;
  mutate: (fn: (user: AppState) => void) => Promise<void>;
}
